### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xHyroM** [xHyroM/bun-discord-bot#14]
- [ ] `mdn` command - search in mozilla documentation
- [x] update `io uring` tag
- [x] `type` in `github` command
